[versions]
# Kotlin
kotlin = "2.4.10"
kotlin-serialization-plugin = "2.4.10"
kotlinx-serialization = "1.11.0"
kotlinx-coroutines = "1.11.0"

# Fabric
loom = "1.17-SNAPSHOT"
fabric-loader = "0.19.3"
fabric-kotlin-loader = "1.13.13+kotlin.2.4.10"
fabric-api = "0.158.0+26.2"

# Deps
yacl = "3.9.6+26.2-fabric"
modmenu = "20.0.1"
sheeplib = "1.5.3+26.2"
noxesium = "3.2.4"
kpresence = "0.6.6"
dev-auth = "1.2.2"

[libraries]
# Fabric
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }

# Deps
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
sheeplib-api = { module = "com.noxcrew.sheeplib:api", version.ref = "sheeplib" }
noxesium-fabric = { module = "com.noxcrew.noxesium:fabric", version.ref = "noxesium" }
dev-auth-fabric = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "dev-auth" }
kpresence = { module = "io.github.vyfor:kpresence", version.ref = "kpresence" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
